project:
  type: website

website:
  description: "Logan Foster's Personal Page"
  site-url: https://zup7mn.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Logan's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zup7mn
      - icon: linkedin
        href: https://www.linkedin.com/in/logan-tyler-foster/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



